create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  customer_name text not null check (char_length(trim(customer_name)) between 1 and 100),
  phone text not null check (phone ~ '^[6-9][0-9]{9}$'),
  address text not null check (char_length(trim(address)) between 5 and 500),
  items jsonb not null check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) > 0),
  subtotal numeric(10, 2) not null check (subtotal >= 0),
  delivery_fee numeric(10, 2) not null check (delivery_fee >= 0),
  total numeric(10, 2) not null check (total = subtotal + delivery_fee),
  payment_method text not null check (payment_method in ('upi', 'cod')),
  payment_status text not null default 'pending'
    check (payment_status in ('pending', 'cash_due', 'paid', 'failed')),
  status text not null default 'new'
    check (status in ('new', 'accepted', 'preparing', 'out_for_delivery', 'delivered', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);

alter table public.orders enable row level security;
revoke all on public.orders from anon, authenticated;
grant select on public.orders to authenticated;
grant update (status, payment_status, updated_at) on public.orders to authenticated;
grant all on public.orders to service_role;

drop policy if exists "Admins can view orders" on public.orders;
create policy "Admins can view orders"
on public.orders for select to authenticated
using ((select public.is_menu_admin()));

drop policy if exists "Admins can update order status" on public.orders;
create policy "Admins can update order status"
on public.orders for update to authenticated
using ((select public.is_menu_admin()))
with check ((select public.is_menu_admin()));

create table if not exists public.order_rate_limits (
  ip_hash text primary key check (ip_hash ~ '^[0-9a-f]{64}$'),
  window_started_at timestamptz not null,
  request_count integer not null check (request_count > 0)
);
alter table public.order_rate_limits enable row level security;
revoke all on public.order_rate_limits from anon, authenticated;
grant all on public.order_rate_limits to service_role;

create or replace function public.consume_order_rate_limit(p_ip_hash text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_now timestamptz := clock_timestamp();
  allowed boolean;
begin
  if p_ip_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'Invalid rate limit key';
  end if;

  insert into public.order_rate_limits as limits (ip_hash, window_started_at, request_count)
  values (p_ip_hash, v_now, 1)
  on conflict (ip_hash) do update
  set
    window_started_at = case
      when limits.window_started_at < v_now - interval '15 minutes'
        then v_now
      else limits.window_started_at
    end,
    request_count = case
      when limits.window_started_at < v_now - interval '15 minutes'
        then 1
      else limits.request_count + 1
    end
  returning request_count <= 8 into allowed;

  return allowed;
end;
$$;

revoke all on function public.consume_order_rate_limit(text) from public, anon, authenticated;
grant execute on function public.consume_order_rate_limit(text) to service_role;
